socket:
  host: 127.0.0.1
  port: 81
  sslProtocol: https
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  upgradeTimeout: 10000
  pingTimeout: 60000
  pingInterval: 25000
logging:
  config: "classpath:logback.xml"